---
linters:
  # TODO: enable this + fix issues.
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml
  # TODO: enable this + fix issues.
  SpaceAroundErbTag:
    enabled: false
  # TF uses tabs.
  SpaceIndentation:
    enabled: false
  # Newlines at end of files depends greatly on the file.
  FinalNewline:
    enabled: false
  # Not relevant.
  ErbSafety:
    enabled: false
  # It's CSS related and not relevant.
  DeprecatedClasses:
    enabled: false
  # It's HTML related and causes false-positives
  SpaceInHtmlTag:
    enabled: false
  # We add multiple blank lines depending on
  # templated code should appear.
  ExtraNewline:
    enabled: false
