--- !ruby/object:Provider::Ansible::Example
dependencies:
  - !ruby/object:Provider::Ansible::Task
    name: gcp_compute_network
    register: network
    code:
      name: <%= dependency_name('network', 'instance') %>
      project: <%= ctx[:project] %>
      auth_kind: <%= ctx[:auth_kind] %>
      service_account_file: <%= ctx[:service_account_file] %>
task: !ruby/object:Provider::Ansible::Task
  name: gcp_redis_instance
  code:
    name: "instance37"
    tier: "STANDARD_HA"
    memory_size_gb: 1
    region: 'us-central1'
    location_id: 'us-central1-a'
    redis_version: "REDIS_3_2"
    display_name: "Ansible Test Instance"
    reserved_ip_range: "192.168.0.0/29"
    labels:
      my_key: my_val
      other_key: other_val
    project: <%= ctx[:project] %>
    auth_kind: <%= ctx[:auth_kind] %>
    service_account_file: <%= ctx[:service_account_file] %>
